# This Docker compose file starts the API server and its associated MongoDB.
# The following commands have to be run from inside the project folder.
# Omit the service name to execute the command for all services.
# Possible service names are: api, mongo
# Start service: docker-compose -f production.yml up <service name> -d
# Restart service: docker-compose -f production.yml restart <service name>
# Stop service: docker-compose -f production.yml down <service name>

version: '3'
services:
  api:
    image: "aseteamblue/thingy-api-blue-docker"
    ports:
     - "443:8080"
    volumes:
     - "./logs/:/usr/src/app/logs/"
     - "/etc/pki/tls/private/:/usr/src/app/certs/"
  mongo:
    image: "mongo:3.4"
    command: --sslMode requireSSL --sslDisabledProtocols TLS1_0,TLS1_1 --sslCAFile /mnt/ThingyRootCA.pem --sslPEMKeyFile /mnt/ThingyDB.pem
    ports:
     - "27017:27017"
    volumes:
     - "/etc/pki/tls/private/:/mnt/"
  redirect:
    image: "hope/redirect-http-to-https"
    ports:
     - "80:80"
