# This Docker compose file starts the API server and its associated MongoDB.
# The following commands have to be run from inside the project folder.
# Start service: docker-compose -f production.yml up -d
# Restart service: docker-compose -f production.yml restart <service name>
# Possible service names are: api, mongo
# Stop service: docker-compose -f production.yml down

version: '3'
services:
  api:
    image: "aseteamblue/thingy-api-blue-docker"
    ports:
     - "9000:8080"
  mongo:
    image: "mongo"
    ports:
     - "27017:27017"
